version : '3.7'
services :
        web :
                container_name : c-nginx
                image : nginx:latest
                ports :
                        - "80:80"
                environment :
                        - NGINX_PORT=80

        redis:
                image: redis
                ports:
                - "6379:6379"
        mysql :
                container_name : c-mysql
                image : mysql:5.6.44
                restart : always
                command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
                volumes :
                        - ./docker/data/mysql:/data/mysql
                environment:
                        - MYSQL_DATABASE=wespace
                        - MYSQL_USER=wespace
                        - MYSQL_ROOT_PASSWORD=wespace
        mongo :
                container_name : c-mongo
                image : mongo:latest
                restart : always
                ports :
                        - "27983:27983"
                volumes :
                        - ./docker/data/mongo:/data/mongo
                environment :
                        - MONGO_INITDB_ROOT_USERNAME=admin
                        - MONGO_INITDB_ROOT_PASSWORD=wespace
        jenkins :
                container_name : c-jenkins
                image : jenkins:latest
                restart : always
                ports :
                        - "8088:8080"

